### ISSUE TITLE
Issue passing too many parameters in the configuration

### ISSUE THREAD

**Issue by glundie** [TimMoore/mojo-executor#22]
Hi,

I am using your plugin to execute the maven-android-plugin with the following code - 

private void executeAPKBuilder(){
        try {
            executeMojo(
                    plugin(
                            groupId("com.jayway.maven.plugins.android.generation2"),
                            artifactId("android-maven-plugin"),
                            version("3.8.1")
                    ),
                    goal("apk"),
                    getConfiguration(),
                    executionEnvironment(
                            project,
                            session,
                            pluginManager
                    )
            );
        } catch (MojoExecutionException e) {
            e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
        }
    }

```
private Xpp3Dom getConfiguration(){
    project.getBuildPlugins().iterator();
    for (Iterator iterator = project.getBuildPlugins().iterator(); iterator.hasNext();) {
        Plugin plugin = (Plugin) iterator.next();
        if("android-maven-plugin".equalsIgnoreCase(plugin.getArtifactId())) {
            return (Xpp3Dom)plugin.getConfiguration();
        }
    }
    return null;
}
```

However, in the pom, the configuration section of the android-maven-plugin contains elements that are not used in this particular goal.  As such, I am receiving a number of errors in a format similar to 

Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.8.1:apk for parameter lint: Cannot find 'lint' in class com.jayway.maven.plugins.android.phase09package.ApkMojo

Is there a property that can be set to so that this scenario is silently consumed?

Thanks in advance,
Gary

**Comment by rnc** [comment]
Can you provide a test case with the current version of the android maven plugin (currently 4.4.3 : https://simpligility.github.io/android-maven-plugin/index.html ) ?

**Comment by rnc** [comment]
I'm closing this ; if its still a problem please provide a test case and reopen a new issue.
