### ISSUE TITLE
Anyway to pass  --quiet option

### ISSUE THREAD

**Issue by dkirrane** [TimMoore/mojo-executor#25]
When running Mojo-Executor I'd like it to be silent. Only print Warning and Errors thrown by the goal being run

`mvn` has a `--quiet` option anyway to use that with Mojo-Executor?

**Comment by TimMoore** [comment]
There's nothing specific to handle the quiet flag.

**Comment by sergiofigueras** [comment]
Hello,

It's not the same problem as yours, but what I've done in my case was to redirect the JVM output to a file at some situations, so for example, I can imagine that if there's some occurrencies that are not warning or errors, please redirect it to another output (may be a file, ex).

It's not a good solution, but it was the only way that I've seen to handle this.

```
PrintStream originalStream = System.out;
    try {
      PrintStream ps = new PrintStream(new FileOutputStream(ERRORPRONE_FILE, true));
      System.setOut(ps);
    } catch (FileNotFoundException e){
      LOGGER.error("ErrorProneRunMojo", e);
      throw new MojoExecutionException(e.getMessage());
    }
//my logic goes here and then I redirect the default outputstream to original
System.setOut(originalStream);

```

Hope that can helps :)

**Comment by rnc** [comment]
Shouldn't any Mojo executed by the mojo-executor get the standard logging framework?

**Comment by rnc** [comment]
PR: https://github.com/TimMoore/mojo-executor/pull/29
