### ISSUE TITLE
mojo-executor 1.5 with maven 3.3.9

### ISSUE THREAD

**Issue by hiddusk** [TimMoore/mojo-executor#31]
Hi,

we are using mojo-executor 1.5 with maven 3.3.9 in one of our plugin
when we used that plugin in application getting below mentioned error

Failed to execute goal com.iggroup.wt.fe.maven:wt-fe-maven-plugin:3.26.0-SNAPSHOT:build-to-webapp (default) on project wt-payments-ui-weblib-desktop: Execution default of goal com.iggroup.wt.fe.maven:wt-fe-maven-plugin:3.26.0-SNAPSHOT:build-to-webapp failed: An API incompatibility was encountered while executing com.iggroup.wt.fe.maven:wt-fe-maven-plugin:3.26.0-SNAPSHOT:build-to-webapp: java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;

NOTE: we are using BuildPluginManager so that mojo-executor will use ExecutionEnvironmentM3.

Could you please update on this issue?

Thanks,
Hidayath.

**Comment by TimMoore** [comment]
Can you use mojo-executor version 2.2.0? Version 1.5 doesn't support Maven 3.1+
