### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by cowwoc** [TimMoore/mojo-executor#43]
Hi,

Version 2.3.0 pulls an outdated version of `org.sonatype.sisu` which breaks compilation on Java9+. Please update your transitive dependency to:

```
<dependency>
	<groupId>org.sonatype.sisu</groupId>
	<artifactId>sisu-inject-plexus</artifactId>
	<version>2.6.0</version>
</dependency>
```

**Comment by cowwoc** [comment]
Closing this for now.

**Comment by rnc** [comment]
@cowwoc Do you need a new release with the fix?

**Comment by cowwoc** [comment]
@rnc No. My code is on 2.3.0 now and the problem no longer shows up. I suspect my original bug report was incorrect or upgrading some other dependency might have fixed it.
