### ISSUE TITLE
default-descriptor fails with ArrayIndexOutOfBoundsException error while invoking same-plugin goals

### ISSUE THREAD

**Issue by marco-brandizi** [TimMoore/mojo-executor#45]
I'm trying to use the mojo executor to develop a new goal for a plugin that is simply the execution of two other already existing goals.

  * [Repository](https://github.com/Rothamsted/neo4j-server-maven-plugin/tree/201901_download)
  * [new goal](https://github.com/Rothamsted/neo4j-server-maven-plugin/blob/201901_download/src/main/java/com/github/harti2006/neo4j/DownloadNeo4jServerMojo.java)

The build fails quite early, with a strange error of default-descriptor failed due to ArrayIndexOutOfBoundsException (see [attached output](https://github.com/TimMoore/mojo-executor/files/2846664/plugin_out.txt)).

If I keep the mojo-executor dependency, without that class that uses it, I don't get the error.

**Comment by TimMoore** [comment]
From Googling the error message, it looks like you need to use a newer version of the asm JAR. For that, you'll need to update maven-plugin-plugin to 3.4.0 or later for compatibility with Java 8 (the latest is 3.6.0).

**Comment by marco-brandizi** [comment]
It worked! Thanks a lot, @TimMoore!
