### ISSUE TITLE
pom.xml compiler plugin not configured

### ISSUE THREAD

**Issue by verhas** [TimMoore/mojo-executor#48]
For me, it seems that the `pom.xml` files are erroneous. The project does not compile with `Apache Maven 3.6.1` because it does not support Java version 1.5 anymore. On the other hand, the parent pom seemingly defines the source and the target to 1.8. But it does not.

What the parent pom does it that it configures a plugin, specifically the 

```
          <groupId>org.apache.maven</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.1</version>
```

plugin, which does not exist. The `groupId` is missing the `.plugins` from the end. It does not cause a compilation problem with Maven 2, because this is just plugin management and as such, it is only declaration. It would cause a problem when the plugin is to be used. But it is not. It is not in the `build/plugin` area in the parent pom and it is not in the children's poms.

This also explains why there is a `//TODO` in the code to upgrade exception handling to Java 7 style. It was not compiling because the actual version was Java 1.5

I did these changes and I could compile the project with the Maven version mentioned above. It probably works, I have not checked.

**Comment by rnc** [comment]
@verhas I presume you are using `master`. According to https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-compiler-plugin 3.8.1 does exist?

**Comment by rnc** [comment]
Let me know if you need a release :-)

**Comment by verhas** [comment]
No. I do not. I actually study the code to learn a bit about this functionality.

I plan to create a plugin that can compile source in the `generate` subdirectory and then execute the code in the generate-sources phase.
