### ISSUE TITLE
Plugin to wrap non-threadsafe plugins

### ISSUE THREAD

**Issue by dhoffer** [TimMoore/mojo-executor#51]
I'm looking for a plugin that could be used to wrap another plugin that is not threadsafe, could this project be enhanced to support this use-case?  I think just a global mutex would need to be added around the non-threadsafe plugin.  The goal being to force the Maven reactor to use the non-threadsafe plugin by one thread at a time even with builds using multiple threads.

**Comment by rnc** [comment]
You submitted PR #52 for this. Apologies for the delay in getting to this. Did you want a release?
