### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lazar-mitrovic** [TimMoore/mojo-executor#57]
Hi,
As the latest release is almost 2 years old, I was wondering if `2.3.2` release was planned?
Biggest unreleased fix (as far as I see) is in PR #52, and it might be a blocker for our use case.

Thanks in advance!
cc: @TimMoore

**Comment by TimMoore** [comment]
@rnc are you still able to do a release for this? Thanks!

**Comment by rnc** [comment]
Sure, I'll get on it :-)

**Comment by rnc** [comment]
2.3.2 now released. Central propagating now...

**Comment by TimMoore** [comment]
Legend! Thanks, @rnc
