### ISSUE TITLE
Repo Secret

### ISSUE THREAD

**Issue by rnc** [TimMoore/mojo-executor#62]
@TimMoore Can you create two repository secrets (`SONATYPE_PASSWORD`) and (`SONATYPE_USERNAME`) in order for snapshots to deploy correctly please? (or you could give me access and I'll do it).

**Comment by TimMoore** [comment]
I created the secrets and re-ran the last pull request merge.

Looks like it worked:

https://github.com/TimMoore/mojo-executor/runs/3511134974?check_suite_focus=true
https://oss.sonatype.org/content/repositories/snapshots/org/twdata/maven/mojo-executor/2.3.3-SNAPSHOT/

I'd be happy to give you admin access, but it looks like that's not possible with a personal repository. I've been thinking about trying to move this to an organization account, anyway. I opened a new issue to discuss: #63
