### ISSUE TITLE
"compile" scoped dependency on slf4j-simple is a bad idea

### ISSUE THREAD

**Issue by yegor256** [TimMoore/mojo-executor#64]
Now you depend on `org.slf4j:slf4j-simple` in "compile" scope, which makes my Maven to put it to classpath and conflict with my own version of slf4j bindings, which are of higher versions. I suggest you move yours to "test" scope.

[Here](https://github.com/TimMoore/mojo-executor/blob/master/pom.xml#L182-L186) just add `<scope>test</scope>`

**Comment by TimMoore** [comment]
Are you sure that's what's happening, @yegor256? The line you've linked to  is in a `dependencyManagement` section in the parent project's POM, so it shouldn't directly affect projects that depend on the library. The only reason it would affect your project's dependencies (as far as I know) is if you're importing the mojo-executor-parent POM.

The actual dependency declared in the library project  does have `test` scope:

https://github.com/TimMoore/mojo-executor/blob/68efa10e9984f32e5f35455b2b5dd518338896df/mojo-executor/pom.xml#L66-L70

**Comment by TimMoore** [comment]
For what it's worth, I wouldn't object to merging a pull request that puts it in `test` scope here, too, but I just don't think it will solve any problems.

**Comment by rnc** [comment]
Can you provide a test case? As @TimMoore says this shouldn't be an issue so I think we need further information.

**Comment by yegor256** [comment]
@TimMoore check this out: https://github.com/cqfn/eo/blob/master/eo-maven-plugin/pom.xml#L103-L107 Try running `mvn dependency:tree` on this project, you will see your jar in `compile` scope

**Comment by rnc** [comment]
@yegor256 Have you tried with 2.3.2 please?

**Comment by TimMoore** [comment]
It looks like this is fixed in 2.3.1: https://github.com/TimMoore/mojo-executor/commit/359b314a735f067b54db5d06cb0f4f4aa94352ac

I'll go ahead and close this on the presumption that it's already fixed, but  @yegor256 let us know if you still have this problem with the latest version.

**Comment by yegor256** [comment]
@TimMoore indeed, it's fixed, thanks!
